//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthorizationPawnshop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyPaymentSchedule
    {
        public int IdSchedule { get; set; }
        public double Summa { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> ActualDueDate { get; set; }
        public int IdEmployee { get; set; }
        public int IdStatus { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Status Status { get; set; }
    }
}
