//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthorizationPawnshop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sold
    {
        public int IdSold { get; set; }
        public Nullable<System.DateTime> DateOfSale { get; set; }
        public double Price { get; set; }
        public int IdEmployee { get; set; }
        public int IdProduct { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Product Product { get; set; }
    }
}
